<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Category_model');
    } 

    /*
     * Listing of category
     */
    function index()
    {
        $data['category'] = $this->Category_model->get_all_category();
        
        $data['_view'] = 'category/index';

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('category/index',$data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new category
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('title','Title','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'parrent_id' => $this->input->post('parrent_id'),
				'title' => $this->input->post('title'),
				'meta_title' => $this->input->post('meta_title'),
				'slug' => $this->input->post('slug'),
				'content' => $this->input->post('content'),
            );
            
            $category_id = $this->Category_model->add_category($params);
            redirect('category/index');
        }
        else
        {            
            $data['_view'] = 'category/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('category/add',$data);
            $this->load->view('template/footer');
        }
    }  

    /*
     * Editing a category
     */
    function edit($id)
    {   
        // check if the category exists before trying to edit it
        $data['category'] = $this->Category_model->get_category($id);
        
        if(isset($data['category']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('title','Title','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'parrent_id' => $this->input->post('parrent_id'),
					'title' => $this->input->post('title'),
					'meta_title' => $this->input->post('meta_title'),
					'slug' => $this->input->post('slug'),
					'content' => $this->input->post('content'),
                );

                $this->Category_model->update_category($id,$params);            
                redirect('category/index');
            }
            else
            {
                $data['_view'] = 'category/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('category/edit',$data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The category you are trying to edit does not exist.');
    } 

    /*
     * Deleting category
     */
    function remove($id)
    {
        $category = $this->Category_model->get_category($id);

        // check if the category exists before trying to delete it
        if(isset($category['id']))
        {
            $this->Category_model->delete_category($id);
            redirect('category/index');
        }
        else
            show_error('The category you are trying to delete does not exist.');
    }
    
}