<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Guru extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Guru_model');
    }

    /*
     * Listing of guru
     */
    function index()
    {
        $data['guru'] = $this->Guru_model->get_all_guru();

        $data['_view'] = 'guru/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('guru/index', $data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new guru
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('email', 'Email', 'valid_email');
        $this->form_validation->set_rules('nomor_induk', 'Nomor Induk', 'numeric');
        $this->form_validation->set_rules('hp', 'Hp', 'numeric');

        if ($this->form_validation->run()) {
            $params = array(
                'id_user' => $this->input->post('id_user'),
                'nama' => $this->input->post('nama'),
                'hp' => $this->input->post('hp'),
                'email' => $this->input->post('email'),
                'nomor_induk' => $this->input->post('nomor_induk'),
                'foto' => $this->input->post('foto'),
                'tempat_lahir' => $this->input->post('tempat_lahir'),
                'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                'alamat' => $this->input->post('alamat'),
                'biografi' => $this->input->post('biografi'),
                'pendidikan' => $this->input->post('pendidikan'),
                'url_fb' => $this->input->post('url_fb'),
                'url_twitter' => $this->input->post('url_twitter'),
                'url_instagram' => $this->input->post('url_instagram'),
                'url_youtube' => $this->input->post('url_youtube'),
            );

            $guru_id = $this->Guru_model->add_guru($params);
            redirect('guru/index');
        } else {
            $data['_view'] = 'guru/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('guru/add', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Editing a guru
     */
    function edit($id)
    {
        // check if the guru exists before trying to edit it
        $data['guru'] = $this->Guru_model->get_guru($id);

        if (isset($data['guru']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('email', 'Email', 'valid_email');
            $this->form_validation->set_rules('nomor_induk', 'Nomor Induk', 'numeric');
            $this->form_validation->set_rules('hp', 'Hp', 'numeric');

            if ($this->form_validation->run()) {
                $params = array(
                    'id_user' => $this->input->post('id_user'),
                    'nama' => $this->input->post('nama'),
                    'hp' => $this->input->post('hp'),
                    'email' => $this->input->post('email'),
                    'nomor_induk' => $this->input->post('nomor_induk'),
                    'foto' => $this->input->post('foto'),
                    'tempat_lahir' => $this->input->post('tempat_lahir'),
                    'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                    'alamat' => $this->input->post('alamat'),
                    'biografi' => $this->input->post('biografi'),
                    'pendidikan' => $this->input->post('pendidikan'),
                    'url_fb' => $this->input->post('url_fb'),
                    'url_twitter' => $this->input->post('url_twitter'),
                    'url_instagram' => $this->input->post('url_instagram'),
                    'url_youtube' => $this->input->post('url_youtube'),
                );

                $this->Guru_model->update_guru($id, $params);
                redirect('guru/index');
            } else {
                $data['_view'] = 'guru/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('guru/edit', $data);
                $this->load->view('template/footer');
            }
        } else
            show_error('The guru you are trying to edit does not exist.');
    }

    /*
     * Deleting guru
     */
    function remove($id)
    {
        $guru = $this->Guru_model->get_guru($id);

        // check if the guru exists before trying to delete it
        if (isset($guru['id'])) {
            $this->Guru_model->delete_guru($id);
            redirect('guru/index');
        } else
            show_error('The guru you are trying to delete does not exist.');
    }
}
