<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

require 'vendor/autoload.php'; //untuk load semua library di folder vendor
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Helper\Sample;

class Mapel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mapel_model');
        $this->load->model('Category_model');
        check_login();
    }

    /*
     * Listing of mapel
     */
    function index()
    {
        $data['script'] = '';

        $data['mapel'] = $this->Mapel_model->get_all_mapel();

        $data['_view'] = 'mapel/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('mapel/index', $data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new mapel
     */
    function add()
    {
        $data['script'] = '';

        $this->load->library('form_validation');

        $this->form_validation->set_rules('nama', 'Nama', 'required|max_length[255]');
        $this->form_validation->set_rules('kode', 'Kode', 'required|max_length[255]');

        if ($this->form_validation->run()) {
            $params = array(
                'nama' => $this->input->post('nama'),
                'kode' => $this->input->post('kode'),
            );

            $mapel_id = $this->Mapel_model->add_mapel($params);

            // tambahkan data kedalam table category
            $category = [
                'title' => $this->input->post('nama'),
                'slug' => str_replace(' ', '-', $this->input->post('kode')), // ganti spasi dengan karakter -
                'content' => 'Kategori ' . $this->input->post('nama'),
            ];

            $category = $this->Category_model->add_category($category);

            redirect('mapel/index');
        } else {
            $data['_view'] = 'mapel/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('mapel/add', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Editing a mapel
     */
    function edit($id)
    {
        $data['script'] = '';

        // check if the mapel exists before trying to edit it
        $data['mapel'] = $this->Mapel_model->get_mapel($id);

        if (isset($data['mapel']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nama', 'Nama', 'required|max_length[255]');
            $this->form_validation->set_rules('kode', 'Kode', 'required|max_length[255]');

            if ($this->form_validation->run()) {
                $params = array(
                    'nama' => $this->input->post('nama'),
                    'kode' => $this->input->post('kode'),
                );

                $this->Mapel_model->update_mapel($id, $params);

                // ubah kelas dan ubah data pada tabel category
                $category = [
                    'title' => $this->input->post('nama'),
                    'slug' => str_replace(' ', '-', $this->input->post('kode')), // ganti spasi dengan karakter -
                    'content' => 'Kategori ' . $this->input->post('nama'),
                ];

                $this->Category_model->update_category($id, $category);

                redirect('mapel/index');
            } else {
                $data['_view'] = 'mapel/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('mapel/edit', $data);
                $this->load->view('template/footer');
            }
        } else
            show_error('The mapel you are trying to edit does not exist.');
    }

    /*
     * Deleting mapel
     */
    function remove($id)
    {
        $mapel = $this->Mapel_model->get_mapel($id);

        // check if the mapel exists before trying to delete it
        if (isset($mapel['id'])) {
            $this->Mapel_model->delete_mapel($id);
            // hapus kategori
            $this->Category_model->delete_category($id);

            redirect('mapel/index');
        } else
            show_error('The mapel you are trying to delete does not exist.');
    }

    function download()
    {
        force_download('downloads/template mapel.xlsx', NULL);
    }

    function do_upload()
    {
        $config['upload_path']          = './uploads/';
        $config['allowed_types']        = 'xlsx|xls|csv';
        $config['file_name']            = 'template_mapel';
        $config['overwrite']            = TRUE;

        $this->load->library('upload', $config);

        if (!$this->upload->do_upload('userfile')) {
            $error = array('error' => $this->upload->display_errors());
            print_r($error);
        } else {
            $data_mapel = [];
            $data_category = [];
            $data = array('upload_data' => $this->upload->data());
            // print_r($data);
            $helper = new Sample();
            $inputFileName = 'uploads/' . $data['upload_data']['file_name'];
            $helper->log('Loading file ' . pathinfo($inputFileName, PATHINFO_BASENAME) . ' using IOFactory to identify the format');
            $spreadsheet = IOFactory::load($inputFileName);
            $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
            // baca data mulai dari baris ke dua
            for ($i = 2; $i < count($sheetData); $i++) {
                $data = [
                    'nama' => $sheetData[$i]['A'],
                    'kode' => $sheetData[$i]['B'],
                ];

                $category = [
                    'title' => $sheetData[$i]['A'],
                    'slug' => str_replace(' ', '-', $sheetData[$i]['B']),
                    'content' => 'Kategori ' . $sheetData[$i]['A'],
                ];

                array_push($data_mapel, $data);
                array_push($data_category, $category);
            }

            // print_r($data_mapel);
            $this->db->insert_batch('mapel', $data_mapel);
            // tambahkan data ke dalam table category
            $this->db->insert_batch('category', $data_category);
            
            redirect('mapel');
        }
    }
}
