<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Mapel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mapel_model');
    }

    /*
     * Listing of mapel
     */
    function index()
    {
        $data['mapel'] = $this->Mapel_model->get_all_mapel();

        $data['_view'] = 'mapel/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('mapel/index', $data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new mapel
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nama', 'Nama', 'required|max_length[255]');
        $this->form_validation->set_rules('kode', 'Kode', 'required|max_length[255]');

        if ($this->form_validation->run()) {
            $params = array(
                'nama' => $this->input->post('nama'),
                'kode' => $this->input->post('kode'),
            );

            $mapel_id = $this->Mapel_model->add_mapel($params);
            redirect('mapel/index');
        } else {
            $data['_view'] = 'mapel/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('mapel/add', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Editing a mapel
     */
    function edit($id)
    {
        // check if the mapel exists before trying to edit it
        $data['mapel'] = $this->Mapel_model->get_mapel($id);

        if (isset($data['mapel']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nama', 'Nama', 'required|max_length[255]');
            $this->form_validation->set_rules('kode', 'Kode', 'required|max_length[255]');

            if ($this->form_validation->run()) {
                $params = array(
                    'nama' => $this->input->post('nama'),
                    'kode' => $this->input->post('kode'),
                );

                $this->Mapel_model->update_mapel($id, $params);
                redirect('mapel/index');
            } else {
                $data['_view'] = 'mapel/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('mapel/edit', $data);
                $this->load->view('template/footer');
            }
        } else
            show_error('The mapel you are trying to edit does not exist.');
    }

    /*
     * Deleting mapel
     */
    function remove($id)
    {
        $mapel = $this->Mapel_model->get_mapel($id);

        // check if the mapel exists before trying to delete it
        if (isset($mapel['id'])) {
            $this->Mapel_model->delete_mapel($id);
            redirect('mapel/index');
        } else
            show_error('The mapel you are trying to delete does not exist.');
    }
}
