<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Post_tag extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Post_tag_model');
        check_login();
    }

    /*
     * Listing of post_tag
     */
    function index()
    {
        $data['post_tag'] = $this->Post_tag_model->get_all_post_tag();

        $data['_view'] = 'post_tag/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('post_tag/index', $data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new post_tag
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'post_id' => $this->input->post('post_id'),
                'tag_id' => $this->input->post('tag_id'),
            );

            $post_tag_id = $this->Post_tag_model->add_post_tag($params);
            redirect('post_tag/index');
        } else {
            $this->load->model('Post_model');
            $data['all_posts'] = $this->Post_model->get_all_posts();

            $this->load->model('Tag_model');
            $data['all_tag'] = $this->Tag_model->get_all_tag();

            $data['_view'] = 'post_tag/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('post_tag/add', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Editing a post_tag
     */
    function edit($id)
    {
        // check if the post_tag exists before trying to edit it
        $data['post_tag'] = $this->Post_tag_model->get_post_tag($id);

        if (isset($data['post_tag']['id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'post_id' => $this->input->post('post_id'),
                    'tag_id' => $this->input->post('tag_id'),
                );

                $this->Post_tag_model->update_post_tag($id, $params);
                redirect('post_tag/index');
            } else {
                $this->load->model('Post_model');
                $data['all_posts'] = $this->Post_model->get_all_posts();

                $this->load->model('Tag_model');
                $data['all_tag'] = $this->Tag_model->get_all_tag();

                $data['_view'] = 'post_tag/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('post_tag/edit', $data);
                $this->load->view('template/footer');
            }
        } else
            show_error('The post_tag you are trying to edit does not exist.');
    }

    /*
     * Deleting post_tag
     */
    function remove($id)
    {
        $post_tag = $this->Post_tag_model->get_post_tag($id);

        // check if the post_tag exists before trying to delete it
        if (isset($post_tag['id'])) {
            $this->Post_tag_model->delete_post_tag($id);
            redirect('post_tag/index');
        } else
            show_error('The post_tag you are trying to delete does not exist.');
    }
}
