<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Profil_sekolah extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Profil_sekolah_model');
	}

	/*
     * Listing of profil_sekolah
     */
	function index()
	{
		$data['profil_sekolah'] = $this->Profil_sekolah_model->get_all_profil_sekolah();

		$data['_view'] = 'profil_sekolah/index';
		$this->load->view('template/header');
		$this->load->view('template/sidebar');
		$this->load->view('profil_sekolah/index', $data);
		$this->load->view('template/footer');
	}

	/*
     * Adding a new profil_sekolah
     */
	function add()
	{
		$this->load->library('form_validation');

		$this->form_validation->set_rules('nama', 'Nama', 'required');
		$this->form_validation->set_rules('npsn', 'Npsn', 'required');
		$this->form_validation->set_rules('logo', 'Logo', 'required');

		if ($this->form_validation->run()) {
			$params = array(
				'nama' => $this->input->post('nama'),
				'jalan' => $this->input->post('jalan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kota' => $this->input->post('kota'),
				'provinsi' => $this->input->post('provinsi'),
				'kodepos' => $this->input->post('kodepos'),
				'telp' => $this->input->post('telp'),
				'email' => $this->input->post('email'),
				'website' => $this->input->post('website'),
				'logo' => $this->input->post('logo'),
				'npsn' => $this->input->post('npsn'),
			);

			$profil_sekolah_id = $this->Profil_sekolah_model->add_profil_sekolah($params);
			// flashdata
			$this->session->set_flashdata('tambah', 'tambah');
			redirect('profil_sekolah/index');
		} else {
			$data['_view'] = 'profil_sekolah/add';
			$this->load->view('template/header');
			$this->load->view('template/sidebar');
			$this->load->view('profil_sekolah/add', $data);
			$this->load->view('template/footer');
		}
	}

	/*
     * Editing a profil_sekolah
     */
	function edit($id)
	{
		// check if the profil_sekolah exists before trying to edit it
		$data['profil_sekolah'] = $this->Profil_sekolah_model->get_profil_sekolah($id);

		if (isset($data['profil_sekolah']['id'])) {
			$this->load->library('form_validation');

			$this->form_validation->set_rules('nama', 'Nama', 'required');
			$this->form_validation->set_rules('npsn', 'Npsn', 'required');
			$this->form_validation->set_rules('logo', 'Logo', 'required');

			if ($this->form_validation->run()) {
				$params = array(
					'nama' => $this->input->post('nama'),
					'jalan' => $this->input->post('jalan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kota' => $this->input->post('kota'),
					'provinsi' => $this->input->post('provinsi'),
					'kodepos' => $this->input->post('kodepos'),
					'telp' => $this->input->post('telp'),
					'email' => $this->input->post('email'),
					'website' => $this->input->post('website'),
					'logo' => $this->input->post('logo'),
					'npsn' => $this->input->post('npsn'),
				);

				$this->Profil_sekolah_model->update_profil_sekolah($id, $params);
				// flashdata
				$this->session->set_flashdata('ubah', 'ubah');
				redirect('profil_sekolah/index');
			} else {
				$data['_view'] = 'profil_sekolah/edit';
				$this->load->view('template/header');
				$this->load->view('template/sidebar');
				$this->load->view('profil_sekolah/edit', $data);
				$this->load->view('template/footer');
			}
		} else
			show_error('The profil_sekolah you are trying to edit does not exist.');
	}

	/*
     * Deleting profil_sekolah
     */
	function remove($id)
	{
		$profil_sekolah = $this->Profil_sekolah_model->get_profil_sekolah($id);

		// check if the profil_sekolah exists before trying to delete it
		if (isset($profil_sekolah['id'])) {
			$this->Profil_sekolah_model->delete_profil_sekolah($id);
			redirect('profil_sekolah/index');
		} else
			show_error('The profil_sekolah you are trying to delete does not exist.');
	}
}
