<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Rombel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rombel_model');
        $this->load->model('Kelas_model');
        check_login();
    }

    /*
     * Listing of rombel
     */
    function index()
    {
        $data['script'] = "$('.select').multiSelect();";

        $data['rombel'] = $this->Rombel_model->get_all_rombel();
        $data['kelas'] = $this->Kelas_model->get_all_kelas();
        $data['_view'] = 'rombel/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('rombel/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Adding a new rombel
     */
    function add()
    {
        $data['script'] = "$('.select').multiSelect();";

        $this->load->library('form_validation');

        $this->form_validation->set_rules('id_kelas', 'Id Kelas', 'required');
        // $this->form_validation->set_rules('id_siswa', 'Id Siswa', 'required');

        if ($this->form_validation->run()) {
            $data = [];
            $id_siswa = $this->input->post('id_siswa[]');
            foreach ($id_siswa as $s) {
                array_push($data, [
                    'id_kelas' => $this->input->post('id_kelas'),
                    'id_siswa' => $s,
                ]);
            }

            print_r($data);
            $this->db->insert_batch('rombel', $data);
            redirect('rombel/index');
        } else {
            $this->load->model('Kelas_model');
            $data['all_kelas'] = $this->Kelas_model->get_all_kelas();

            // $this->load->model('Siswa_model');
            $users = $this->ion_auth->users('siswa')->result_array();
            // $data['all_siswa'] = $this->Siswa_model->get_all_siswa();

            $siswa = $this->Rombel_model->get_siswa();
            // print_r($siswa);
            $data['users'] = $siswa;

            $data['_view'] = 'rombel/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('rombel/add', $data);
            $this->load->view('template/footer', $data);
        }
    }

    /*
     * Editing a rombel
     */
    function edit($id_kelas)
    {
        $data['script'] = "$('.select').multiSelect();";

        $data['all_kelas'] = $this->Kelas_model->get_all_kelas();
        $data['rombel'] = $this->Rombel_model->get_siswa_by_rombel($id_kelas);
        $data['id_kelas'] = $id_kelas;

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('rombel/edit', $data);
        $this->load->view('template/footer', $data);
    }

    function update()
    {
        $data = [];
        $siswa = $this->input->post('id_siswa[]');
        $id_kelas = $this->input->post('id_kelas');
        // delete siswa
        $this->db->delete('rombel', ['id_kelas' => $id_kelas]);

        foreach ($siswa as $s) {
            array_push($data, [
                'id_kelas' => $id_kelas,
                'id_siswa' => $s,
            ]);
        }
        // print_r($data);
        $this->db->insert_batch('rombel', $data);
        redirect('rombel');
    }

    /*
     * Deleting rombel
     */
    function remove($id)
    {
        $rombel = $this->Rombel_model->get_rombel($id);

        // check if the rombel exists before trying to delete it
        if (isset($rombel['id'])) {
            $this->Rombel_model->delete_rombel($id);
            redirect('rombel/index');
        } else
            show_error('The rombel you are trying to delete does not exist.');
    }
}
