<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Siswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
    } 

    /*
     * Listing of siswa
     */
    function index()
    {
        $data['siswa'] = $this->Siswa_model->get_all_siswa();
        
        $data['_view'] = 'siswa/index';
        $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('siswa/index', $data);
                $this->load->view('template/footer');
    }

    /*
     * Adding a new siswa
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('email','Email','required|valid_email');
		$this->form_validation->set_rules('password','Password','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'email' => $this->input->post('email'),
				'nomor_induk' => $this->input->post('nomor_induk'),
				'foto' => $this->input->post('foto'),
            );
            
            $siswa_id = $this->Siswa_model->add_siswa($params);
            redirect('siswa/index');
        }
        else
        {            
            $data['_view'] = 'siswa/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('siswa/add', $data);
            $this->load->view('template/footer');
        }
    }  

    /*
     * Editing a siswa
     */
    function edit($id)
    {   
        // check if the siswa exists before trying to edit it
        $data['siswa'] = $this->Siswa_model->get_siswa($id);
        
        if(isset($data['siswa']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('email','Email','required|valid_email');
			$this->form_validation->set_rules('password','Password','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'email' => $this->input->post('email'),
					'nomor_induk' => $this->input->post('nomor_induk'),
					'foto' => $this->input->post('foto'),
                );

                $this->Siswa_model->update_siswa($id,$params);            
                redirect('siswa/index');
            }
            else
            {
                $data['_view'] = 'siswa/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('siswa/edit', $data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The siswa you are trying to edit does not exist.');
    } 

    /*
     * Deleting siswa
     */
    function remove($id)
    {
        $siswa = $this->Siswa_model->get_siswa($id);

        // check if the siswa exists before trying to delete it
        if(isset($siswa['id']))
        {
            $this->Siswa_model->delete_siswa($id);
            redirect('siswa/index');
        }
        else
            show_error('The siswa you are trying to delete does not exist.');
    }
    
}