<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tag extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tag_model');
        check_login();
    } 

    /*
     * Listing of tag
     */
    function index()
    {
        $data['tag'] = $this->Tag_model->get_all_tag();
        
        $data['_view'] = 'tag/index';

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('tag/index',$data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new tag
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('title','Title','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'title' => $this->input->post('title'),
				'meta_title' => $this->input->post('meta_title'),
				'slug' => $this->input->post('slug'),
				'content' => $this->input->post('content'),
            );
            
            $tag_id = $this->Tag_model->add_tag($params);
            redirect('tag/index');
        }
        else
        {            
            $data['_view'] = 'tag/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('tag/add',$data);
            $this->load->view('template/footer');
        }
    }  

    /*
     * Editing a tag
     */
    function edit($id)
    {   
        // check if the tag exists before trying to edit it
        $data['tag'] = $this->Tag_model->get_tag($id);
        
        if(isset($data['tag']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('title','Title','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'title' => $this->input->post('title'),
					'meta_title' => $this->input->post('meta_title'),
					'slug' => $this->input->post('slug'),
					'content' => $this->input->post('content'),
                );

                $this->Tag_model->update_tag($id,$params);            
                redirect('tag/index');
            }
            else
            {
                $data['_view'] = 'tag/edit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('tag/edit',$data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The tag you are trying to edit does not exist.');
    } 

    /*
     * Deleting tag
     */
    function remove($id)
    {
        $tag = $this->Tag_model->get_tag($id);

        // check if the tag exists before trying to delete it
        if(isset($tag['id']))
        {
            $this->Tag_model->delete_tag($id);
            redirect('tag/index');
        }
        else
            show_error('The tag you are trying to delete does not exist.');
    }
    
}