<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Ujian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ujian_model');
        $this->load->model('Category_model');
        $this->load->model('Tag_model');
        check_login();
    }

    function index()
    {
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/index');
        $this->load->view('template/footer');
    }

    function add()
    {
        $data['all_category'] = $this->Category_model->get_all_category_join_pengajar();
        $data['all_tag'] = $this->Tag_model->get_all_tag_join_pengajar();
        $data['js'] = $this->load->view('ujian/js_add', $data, true);

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/add', $data);
        $this->load->view('template/footer');
    }

    function get_soal()
    {
        $author_id = user_info()['id'];
        $category = 2;
        $tag = 3;
        $soal = $this->Ujian_model->get_soal($author_id, $category, $tag);
        echo json_encode($soal);
    }

    function get_ujian()
    {
        $ujian = $this->Ujian_model->get_ujian();
        echo json_encode($ujian);
    }
}
