<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Ujian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->driver('cache', array('adapter' => 'apc', 'backup' => 'file'));
        $this->load->library('encryption');
        $this->load->model('Ujian_model');
        $this->load->model('Category_model');
        $this->load->model('Tag_model');
        $this->load->model('Soal_model');

        check_login();
    }

    function index()
    {
        $data['all_ujian'] = $this->Ujian_model->get_all_ujian();

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/index', $data);
        $this->load->view('template/footer');
    }

    function add()
    {
        $data['all_category'] = $this->Category_model->get_all_category_join_pengajar();
        $data['all_tag'] = $this->Tag_model->get_all_tag_join_pengajar();
        $data['js'] = $this->load->view('ujian/js_add', $data, true);

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/add', $data);
        $this->load->view('template/footer');
    }


    function load_soal()
    {
        $id = $this->input->post('soal_id');
        $soal = $this->Ujian_model->load_soal($id);
        echo json_encode($soal);
    }

    function get_ujian()
    {
        $ujian = $this->Ujian_model->get_ujian();
        echo json_encode($ujian);
    }

    function save_soal()
    {
        $jenis_soal = $this->input->post('jenis_soal');
        if ($jenis_soal == 1) {
            // jika soal pilihan ganda
            $params = array(
                'mapel_id' => $this->input->post('mapel_id'),
                'tingkat' => $this->input->post('tingkat'),
                'jenis_soal' => $this->input->post('jenis_soal'),
                'author_id' => user_info()['id'],
                'created_at' => datetime_now(),
                'soal' => $this->input->post('soal'),
                'skor' => $this->input->post('skor'),
                'petunjuk' => $this->input->post('petunjuk'),
                'kunci' => $this->input->post('kunci[1]'), // ambil array ke-1
                'pembahasan' => $this->input->post('pembahasan'),
                'opsi' => json_encode([
                    'a' => $this->input->post('opsi[0]'),
                    'b' => $this->input->post('opsi[1]'),
                    'c' => $this->input->post('opsi[2]'),
                    'd' => $this->input->post('opsi[3]'),
                ]),
            );
        } else {
            // jika soal isian
            $params = array(
                'mapel_id' => $this->input->post('mapel_id'),
                'tingkat' => $this->input->post('tingkat'),
                'jenis_soal' => $this->input->post('jenis_soal'),
                'author_id' => user_info()['id'],
                'created_at' => datetime_now(),
                'soal' => $this->input->post('soal'),
                'skor' => $this->input->post('skor'),
                'petunjuk' => $this->input->post('petunjuk'),
                'kunci' => $this->input->post('kunci[0]'), // ambil array ke-0
                'pembahasan' => $this->input->post('pembahasan'),
                'opsi' => null,
            );
        }

        $soal_id = $this->Soal_model->add_soal($params);
        echo json_encode($soal_id);
    }

    function save_ujian()
    {
        $params = [
            'author_id' => user_info()['id'],
            'created_at' => datetime_now(),
            'mapel_id' => $this->input->post('category_id'),
            'kelas_tingkat' => $this->input->post('kelas_tingkat'),
            'nama_ujian' => $this->input->post('nama_ujian'),
            'token' => generateRandomString(),
            'waktu_selesai' => $this->input->post('waktu_selesai'),
            'durasi' => $this->input->post('durasi'),
        ];

        $ujian_id = $this->Ujian_model->save_ujian($params);
        redirect('ujian/soalujian/ujian_id-' . $ujian_id . '-tingkat-' . $params['kelas_tingkat'] . '-mapel_id-' . $params['mapel_id']);
    }

    function soalujian($url)
    {
        $url_params = explode('-', $url);
        $ujian_id = $url_params[1];
        $tingkat = $url_params[3];
        $mapel_id = $url_params[5];

        $data['ujian_id'] = $ujian_id;
        $data['all_soalujian'] = $this->Ujian_model->get_soal_ujian($ujian_id);
        $data['all_soal'] = $this->Ujian_model->all_soal($tingkat, $mapel_id);
        $data['all_category'] = $this->Category_model->get_all_category_join_pengajar();
        $data['all_tag'] = $this->Tag_model->get_all_tag_join_pengajar();
        $data['js'] = $this->load->view('ujian/js_soalujian', $data, true);

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/soalujian', $data);
        $this->load->view('template/footer');
    }

    function add_soalujian()
    {
        $params = [
            'soal_id' => $this->input->post('soal_id'),
            'ujian_id' => $this->input->post('ujian_id'),
        ];

        $soalujian_id = $this->Ujian_model->add_soalujian($params);
        // tampilkan data soal yang ditambahkan
        $data = [
            'soalujian_id' => $soalujian_id,
            'soal_id' => $this->input->post('soal_id'),
            'ujian_id' => $this->input->post('ujian_id'),
        ];

        echo json_encode($data);
    }

    function delete_soalujian()
    {
        $soal_id = $this->input->post('soal_id');
        $this->db->delete('soal_ujian', ['soal_id' => $soal_id]);
        echo json_encode('deleted');
    }

    function edit($id)
    {
        $data['ujian'] = $this->Ujian_model->get_ujian($id);
        $data['soal_ujian'] = $this->Ujian_model->get_soal_ujian($id);
        $data['all_category'] = $this->Category_model->get_all_category_join_pengajar();
        $data['all_tag'] = $this->Tag_model->get_all_tag_join_pengajar();
        $data['js'] = $this->load->view('ujian/js_add', $data, true);

        // echo json_encode($data['ujian']);
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/edit', $data);
        $this->load->view('template/footer');
    }

    function update_ujian($id)
    {
        $params = [
            // 'author_id' => user_info()['id'],
            // 'created_at' => datetime_now(),
            'mapel_id' => $this->input->post('category_id'),
            'kelas_tingkat' => $this->input->post('kelas_tingkat'),
            'nama_ujian' => $this->input->post('nama_ujian'),
            // 'token' => generateRandomString(),
            'waktu_selesai' => $this->input->post('waktu_selesai'),
            'durasi' => $this->input->post('durasi'),
        ];

        $this->Ujian_model->update_ujian($id, $params);
        redirect('ujian/soalujian/ujian_id-' . $id . '-tingkat-' . $params['kelas_tingkat'] . '-mapel_id-' . $params['mapel_id']);
    }

    function delete_ujian($id)
    {
        $this->db->delete('ujian', ['id' => $id]);
        $this->db->delete('soal_ujian', ['ujian_id' => $id]);
        redirect('ujian');
    }

    function view($id)
    {
        $data['ujian'] = $this->Ujian_model->get_ujian($id);
        $data['all_category'] = $this->Category_model->get_all_category();
        $data['js'] = $this->load->view('ujian/js_view', $data, true);

        $this->load->view('template/top-nav/header');
        $this->load->view('template/top-nav/nav');
        $this->load->view('ujian/view_ujian', $data);
        $this->load->view('template/footer');
    }

    function cektoken()
    {
        $ujian_id = $this->input->post('ujian_id');
		$token = $this->input->post('token');
		$cek = $this->Ujian_model->get_ujian($ujian_id);
        
        if(strtolower($token) == strtolower($cek['token'])){
            $data = [
                'status' => true,
                'url_encrypted' => urlencode($this->encryption->encrypt($ujian_id)),
            ];
        } else {
            $data = [
                'status' => false,
            ];
        }
		echo json_encode($data);
    }

    function do_ujian()
    {
        $key = $this->input->get('key', true);
        $id  = $this->encryption->decrypt(rawurldecode($key));
        
        $data['ujian'] = $this->Ujian_model->get_ujian($id);
        $data['all_soal'] = $this->Ujian_model->get_soal_ujian($id);
        shuffle($data['all_soal']);
        $data['soal_pertama'] = $data['all_soal'][0];
        $data['js'] = $this->load->view('ujian/js_doujian', $data, true);
        $data['tes'] = 'tes';

        // acak dulu soalnya

        // echo json_encode($data);
        // die;
        $this->load->view('template/top-nav/header');
        $this->load->view('template/top-nav/nav');
        $this->load->view('ujian/do_ujian', $data);
        $this->load->view('template/footer');
    }

    function save_cache_jawab()
    {
        $soal_id = $this->input->post('soal_id');
        $jawab = $this->input->post('jawab');
        $this->cache->save($soal_id, $jawab);
        echo json_encode('saved');
    }

    function get_cache_jawab()
    {
        $soal_id = $this->input->post('soal_id');
        $jawaban = $this->cache->get($soal_id);
        echo json_encode($jawaban);
    }

    function koreksi_ujian()
    {
        $ujian_id = $this->input->post('ujian_id');
        $data = $this->input->post('soal_id');
        $jml_benar = 0;
        $jml_salah = 0;
        $nilai = 0;
        $result = [];
        $status = '';
        // pecah data soal id nya untuk mendapatkan masing-masing jawaban yg sudah tersimpan di cache
        foreach($data as $d){
            $jawaban = $this->cache->get($d);
            $soal = $this->Ujian_model->load_soal($d);
            // var_dump($soal);
            // koreksi soalnya
            if($jawaban == $soal['kunci']){
                $nilai =+ $soal['skor'];
                $status = 'benar';
                $jml_benar =+ 1;
            } else {
                $status = 'salah';
                $jml_salah =+ 1;
            }

            // push data masing-masing soal yang sudah dijawab
            array_push($result, [
                'soal_id' => $soal['id'],
                'jawaban' => $jawaban,
                'status' => $status,
            ]);
        }
        $data = [
            'siswa_id' => user_info()['id'],
            'ujian_id' => $ujian_id,
            'waktu_ujian' => datetime_now(),
            'jumlah_benar' => $jml_benar,
            'jumlah_salah' => $jml_salah,
            'nilai' => $nilai,
            'history' => json_encode($result),
        ];

        $this->db->insert('result_ujian', $data);
        echo json_encode($data);
    }

    function result_ujian($ujian_id)
    {
        $data['ujian'] = $this->Ujian_model->get_ujian($ujian_id);
        $data['result'] = $this->Ujian_model->get_result($ujian_id);
        // $data['js'] = $this->load->view('ujian/js_add', $data, true);

        // echo json_encode($data['ujian']);
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('ujian/result_ujian', $data);
        $this->load->view('template/footer');
    }
}
