<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Guru_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get guru by id
     */
    function get_guru($id)
    {
        return $this->db->get_where('guru',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all guru
     */
    function get_all_guru()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('guru')->result_array();
    }
        
    /*
     * function to add new guru
     */
    function add_guru($params)
    {
        $this->db->insert('guru',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update guru
     */
    function update_guru($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('guru',$params);
    }
    
    /*
     * function to delete guru
     */
    function delete_guru($id)
    {
        return $this->db->delete('guru',array('id'=>$id));
    }
}