<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nilai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_my_class()
    {
        $user_id = user_info()['id'];

        return $this->db->select('mapel.id as mapel_id, mapel.nama as nama_mapel, kelas.id as kelas_id, kelas.nama as nama_kelas')
        ->from('pengajar')
        ->where('pengajar.id_guru', $user_id)
        ->join('mapel', 'mapel.id = pengajar.id_mapel')
        ->join('kelas', 'kelas.id = pengajar.id_kelas')
        ->get()
        ->result_array();
    }

    function get_post_by_category_and_tag($category_id, $tag_id)
    {
        $user_id = user_info()['id'];
        return $this->db->select('posts.id as post_id, posts.title as post_title')
        ->from('posts')
        ->join('post_category', 'post_category.post_id = posts.id')
        ->join('post_tag', 'post_tag.post_id = posts.id')
        ->where('post_category.category_id', $category_id)
        ->where('post_tag.tag_id', $tag_id)
        ->where('posts.jenis', 'tugas')
        ->get()
        ->result_array();
    }

    function get_nilai_all_siswa_by_post($siswa_id, $post_id)
    {
        return $this->db->select('*')
        ->from('nilai')
        ->where('nilai.post_id', $post_id)
        ->where('nilai.siswa_id', $siswa_id)
        ->get()
        ->result_array();
    }

    function get_nilai_rerata($siswa_id, $category_id)
    {
        return $this->db->select('nilai.*, avg(nilai.nilai) as rerata')
        ->from('post_category')
        ->where('post_category.category_id', $category_id)
        ->join('posts', 'posts.id = post_category.post_id')
        ->join('nilai', 'nilai.post_id = posts.id')
        ->where('nilai.siswa_id', $siswa_id)
        ->get()
        ->row_array();
    }

    function get_all_nilai()
    {
        $user_id = user_info()['id'];
        $this->db->select('posts.id as post_id, post_category.category_id, post_tag.tag_id, users.id as siswa_id, nilai.nilai, nilai.keterangan')
            ->from('posts')
            ->where('author_id', $user_id)
            ->join('post_category', 'post_category.post_id = posts.id')
            ->join('post_tag', 'post_tag.post_id = posts.id')
            // ->join('kelas', 'kelas.id = post_tag.tag_id')
            ->join('rombel', 'rombel.id_kelas = post_tag.tag_id')
            ->join('users', 'users.id = rombel.id_siswa')
            ->join('nilai', 'nilai.siswa_id = users.id', 'left')
            ->order_by('siswa_id', 'asc')
            ->order_by('post_id','asc')
            ->get()->result_array();
    }
}
