<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nilai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_my_class()
    {
        $user_id = user_info()['id'];

        return $this->db->select('mapel.id as mapel_id, mapel.nama as nama_mapel, kelas.id as kelas_id, kelas.nama as nama_kelas')
        ->from('pengajar')
        ->where('pengajar.id_guru', $user_id)
        ->join('mapel', 'mapel.id = pengajar.id_mapel')
        ->join('kelas', 'kelas.id = pengajar.id_kelas')
        ->get()
        ->result_array();
    }

    function get_post_by_category_and_tag($category_id, $tag_id)
    {
        $user_id = user_info()['id'];
        return $this->db->select('posts.id as post_id, posts.title as post_title')
        ->from('posts')
        ->join('post_category', 'post_category.post_id = posts.id')
        ->join('post_tag', 'post_tag.post_id = posts.id')
        ->where('post_category.category_id', $category_id)
        ->where('post_tag.tag_id', $tag_id)
        ->where('posts.jenis', 'tugas')
        ->get()
        ->result_array();
    }

    function get_nilai_all_siswa_by_post($siswa_id, $post_id)
    {
        return $this->db->select('*')
        ->from('nilai')
        ->where('nilai.post_id', $post_id)
        ->where('nilai.siswa_id', $siswa_id)
        ->get()
        ->result_array();
    }
}
