<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengajar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengajar by id
     */
    function get_pengajar($id)
    {
        return $this->db->get_where('pengajar',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all pengajar
     */
    function get_all_pengajar()
    {
        return $this->db->select('users.first_name, users.id')
        ->from('pengajar')
        ->join('users', 'users.id = pengajar.id_guru')
        ->group_by('users.first_name')
        ->get()
        ->result_array();
    }
        
    /*
     * function to add new pengajar
     */
    function add_pengajar($params)
    {
        $this->db->insert('pengajar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengajar
     */
    function update_pengajar($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pengajar',$params);
    }
    
    /*
     * function to delete pengajar
     */
    function delete_pengajar($id)
    {
        return $this->db->delete('pengajar',array('id'=>$id));
    }
    
    function delete_mapel($id)
    {
        return $this->db->delete('pengajar',array('id_mapel'=>$id));
    }

    function get_mapel($id_guru)
    {
        return $this->db->select('mapel.nama as nama_mapel, mapel.kode as kode_mapel, kelas.nama as nama_kelas, pengajar.id as id')
        ->from('pengajar')
        ->join('kelas', 'pengajar.id_kelas = kelas.id')
        ->join('mapel', 'pengajar.id_mapel = mapel.id')
        ->where('pengajar.id_guru', $id_guru)
        ->order_by('nama_mapel', 'asc')
        ->get()
        ->result_array();
    }

    function get_mapel_for_edit($id_guru)
    {
        return $this->db->select('mapel.id as id_mapel, mapel.nama as nama_mapel, mapel.kode as kode_mapel')
        ->from('pengajar')
        ->join('mapel', 'pengajar.id_mapel = mapel.id')
        ->where('pengajar.id_guru', $id_guru)
        ->group_by('nama_mapel')
        ->get()
        ->result_array();
    }

    function get_kelas_by_mapel($id_mapel)
    {
        return $this->db->select('kelas.id, kelas.nama, pengajar.id_mapel, pengajar.id_guru')
        ->from('kelas')
        ->join('pengajar', 'pengajar.id_kelas = kelas.id and pengajar.id_mapel ='. $id_mapel, 'left')
        ->get()
        ->result_array();

        // return $this->db->last_query();
    }
}
