<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Post_tag_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get post_tag by id
     */
    function get_post_tag($id)
    {
        return $this->db->get_where('post_tag',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all post_tag
     */
    function get_all_post_tag()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('post_tag')->result_array();
    }
        
    /*
     * function to add new post_tag
     */
    function add_post_tag($params)
    {
        $this->db->insert('post_tag',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update post_tag
     */
    function update_post_tag($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('post_tag',$params);
    }

    function update_post_tag_by_post_id($post_id,$params)
    {
        // hapus dulu semua tag yang terkait dengan post id
        $this->db->delete('post_tag', ['post_id' => $post_id]);
        // timpa dengan data tag yang baru
        $this->db->insert('post_tag',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to delete post_tag
     */
    function delete_post_tag($id)
    {
        return $this->db->delete('post_tag',array('id'=>$id));
    }
}