<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Posts_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_category_by()
    {
        $id_user = user_info()['id'];
        return $this->db->select('mapel.*')
        ->from('pengajar')
        ->where('pengajar.id_guru', $id_user)
        ->join('mapel', 'mapel.id = pengajar.id_mapel')
        ->group_by('mapel.nama')
        ->get()->result_array();
    }

    function get_tag_by()
    {
        $id_user = user_info()['id'];
        return $this->db->select('kelas.*')
        ->from('pengajar')
        ->where('pengajar.id_guru', $id_user)
        ->join('kelas', 'kelas.id = pengajar.id_kelas')
        ->get()->result_array();
    }

    function add_posts($params)
    {
        $this->db->insert('posts',$params);
        return $this->db->insert_id();
    }

    function add_posts_category($params)
    {
        $this->db->insert('post_category',$params);
        return $this->db->insert_id();   
    }

    function add_posts_tag($params)
    {
        $this->db->insert('post_tag',$params);
        return $this->db->insert_id();   
    }
}
