<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Profil_sekolah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get profil_sekolah by id
     */
    function get_profil_sekolah($id)
    {
        return $this->db->get_where('profil_sekolah',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all profil_sekolah
     */
    function get_all_profil_sekolah()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('profil_sekolah')->result_array();
    }
        
    /*
     * function to add new profil_sekolah
     */
    function add_profil_sekolah($params)
    {
        $this->db->insert('profil_sekolah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update profil_sekolah
     */
    function update_profil_sekolah($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('profil_sekolah',$params);
    }
    
    /*
     * function to delete profil_sekolah
     */
    function delete_profil_sekolah($id)
    {
        return $this->db->delete('profil_sekolah',array('id'=>$id));
    }
}