<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Soal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get soal by id
     */
    function get_soal($id)
    {
        // return $this->db->get_where('soal',array('id'=>$id))->row_array();
        // return $this->db->select('*')
        return $this->db->select('*')
        ->from('soal')
        ->where('id', $id)
        ->get()
        ->row_array();
    }
        
    /*
     * Get all soal
     */
    function get_all_soal()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('soal')->result_array();
    }
        
    /*
     * function to add new soal
     */
    function add_soal($params)
    {
        $this->db->insert('soal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update soal
     */
    function update_soal($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('soal',$params);
    }
    
    /*
     * function to delete soal
     */
    function delete_soal($id)
    {
        return $this->db->delete('soal',array('id'=>$id));
    }

    function get_mapel()
    {
        $user_id = user_info()['id'];
        return $this->db->select('mapel.id, mapel.nama')
        ->from('pengajar')
        ->where('pengajar.id_guru', $user_id)
        ->join('mapel', 'mapel.id = pengajar.id_mapel')
        ->group_by('pengajar.id_mapel')
        ->get()
        ->result_array();
    }
}