<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tags_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_all_tags()
    {
        $this->db->order_by('title', 'asc');
        return $this->db->get('tag')->result_array(); 
    }

    function add_tag($params)
    {
        $this->db->insert('tag',$params);
        return $this->db->insert_id();
    }

    function update_tag($id, $params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tag',$params);
    }

    function delete_tag($id)
    {
        return $this->db->delete('tag',array('id'=>$id));
    }

    function get_tag($id)
    {
        return $this->db->get_where('tag',array('id'=>$id))->row_array();
    }
}